### ISSUE TITLE
Is it possible to use keys for both $data and $dataType?

### ISSUE THREAD

**Issue by 4thguy** [a1phanumeric/PHP-MySQL-Class#52]
As SecureData is currently written, the function loops to the $key of $data, but references $dataType through an $i variable that is being incremented separately.

Personally I prefer the approach where $dataType contains a list of $data variables, like in this example:

    $data = [
        'user' => 'myUserName',
        'password' => 'password',
        'email' => 'user@example.org'
    ];
    $dataType = [
        'user' => 'str',
        'password' => 'str',
        'email' => 'email'
    ];

that way, we can simply loop through $data, use

    $data[$key] = $this->CleanData($data[$key], $types[$key]);

**Comment by kingkarki** [comment]
i m also having same issue.

**Comment by a1phanumeric** [comment]
This shouldn't be needed now, as I've provided the PDO class which automatically secures your variables.
