### ISSUE TITLE
method add_table_prefix not found

### ISSUE THREAD

**Issue by DatCGI2net** [a1phanumeric/PHP-MySQL-Class#56]
Thanks for your class. I have used it today but when I use the method exist_table, I got the error at line 43 class.DBDPO.php. That is the method add_table_prefix does not exists.

Thanks!

Dat

**Comment by thejwalker** [comment]
I forked, fixed and issued a pull request.. that method is missing so I just removed the call.

https://github.com/thejwalker/PHP-MySQL-Class
