### ISSUE TITLE
Return errors from database queries

### ISSUE THREAD

**Issue by gabrielschuck** [a1phanumeric/PHP-MySQL-Class#63]
I really liked this class to use mysql with PDO, but I really need it to return the errors generated by SQL queries.
Before that I used with the php mysqli extension procedurally, but I think there are many unnecessary lines to make prepared statements and I did not want to make my applications vulnerable. This class has already helped me a lot in this, now only need to return the errors of mysql queries.
Thank you!

**Comment by LegitSoulja** [comment]
@gabrielschuck check out https://github.com/LegitSoulja/SlickInject

**Comment by gabrielschuck** [comment]
#LegitSoulja, Excellent! I'm already doing tests and it seems to be a lot easier to work with. Thank you! Xd
